version: '3'
services:
  load_balancer:
    build: ./load_balancer
    ports:
      - "8080:8080"
    container_name: load_balancer
  worker_one:
    build: ./worker_1
    ports:
      - "8081:8080"
    container_name: worker_1
  worker_two:
    build: ./worker_2
    ports:
      - "8082:8080"
    container_name: worker_2 
  worker_three:
    build: ./worker_3
    ports:
      - "8083:8080"
    container_name: worker_3  
